# Config documentation is available at https://dev.bukkit.org/projects/simpleegg/pages/configuration
update-checks: true
show-tag: true
exchange-mode: item
consumed-item: DIAMOND
consumed-item-name: Diamonds
consumed-item-amount: 5
vault-cost: 100
egg-refund: true
