main: io.github.redpanda4552.SimpleEgg.Main
name: SimpleEgg
version: 0.4.0
author: bdubz4552
description: A plugin to allow the capture and conversion of living entites to spawn eggs.
softdepend: [Vault]
api-version: 1.13

commands:
    simpleegg:
        description: Help command for SimpleEgg
        usage: /simpleegg
        aliases: se

permissions:
    #Global
    SimpleEgg.*:
        children:
            SimpleEgg.passive: true
            SimpleEgg.villager: true
            SimpleEgg.tameable: true
            SimpleEgg.monster: true
            SimpleEgg.owner-override: true
            SimpleEgg.steal: true
            SimpleEgg.auto-tame: true
            SimpleEgg.update-notify: true

    #Admin
    SimpleEgg.update-notify:
      description: Allow players to be notified of updates upon login
    SimpleEgg.reload:
      description: Allow players to reload the plugin

    #Passive
    SimpleEgg.passive:
        children:
            SimpleEgg.cow: true
            SimpleEgg.pig: true
            SimpleEgg.chicken: true
            SimpleEgg.sheep: true
            SimpleEgg.mushroomcow: true
            SimpleEgg.rabbit: true
            SimpleEgg.bat: true
            SimpleEgg.squid: true
            SimpleEgg.polarbear: true
            SimpleEgg.snowman: true
            SimpleEgg.irongolem: true
    SimpleEgg.cow:
        description: Allows capturing of this mob
    SimpleEgg.pig:
        description: Allows capturing of this mob
    SimpleEgg.chicken:
        description: Allows capturing of this mob
    SimpleEgg.sheep:
        description: Allows capturing of this mob
    SimpleEgg.mushroomcow:
        description: Allows capturing of this mob
    SimpleEgg.rabbit:
        description: Allows capturing of this mob
    SimpleEgg.bat:
        description: Allows capturing of this mob
    SimpleEgg.squid:
        description: Allows capturing of this mob
    SimpleEgg.polarbear:
        description: Allows capturing of this mob
    SimpleEgg.snowman:
        description: Allows capturing of this mob
    SimpleEgg.irongolem:
        description: Allows capturing of this mob

    #Villager
    SimpleEgg.villager:
        description: Allows capturing of this mob

    #Tameable
    SimpleEgg.tameable:
        children:
            SimpleEgg.horse: true
            SimpleEgg.donkey: true
            SimpleEgg.mule: true
            SimpleEgg.zombiehorse: true
            SimpleEgg.skeletonhorse: true
            SimpleEgg.llama: true
            SimpleEgg.wolf: true
            SimpleEgg.ocelot: true
            SimpleEgg.parrot: true
    SimpleEgg.horse:
        description: Allows capturing of this mob
    SimpleEgg.donkey:
        description: Allows capturing of this mob
    SimpleEgg.mule:
        description: Allows capturing of this mob
    SimpleEgg.zombiehorse:
        description: Allows capturing of this mob
    SimpleEgg.skeletonhorse:
        description: Allows capturing of this mob
    SimpleEgg.llama:
        description: Allows capturing of this mob
    SimpleEgg.wolf:
        description: Allows capturing of this mob
    SimpleEgg.ocelot:
        description: Allows capturing of this mob
    SimpleEgg.parrot:
        description: Allows capturing of this mob

    #Monsters
    SimpleEgg.monster:
        children:
            SimpleEgg.magmacube: true
            SimpleEgg.blaze: true
            SimpleEgg.ghast: true
            SimpleEgg.pigzombie: true
            SimpleEgg.spider: true
            SimpleEgg.cavespider: true
            SimpleEgg.zombie: true
            SimpleEgg.husk: true
            SimpleEgg.zombievillager: true
            SimpleEgg.skeleton: true
            SimpleEgg.witherskeleton: true
            SimpleEgg.creeper: true
            SimpleEgg.witch: true
            SimpleEgg.enderman: true
            SimpleEgg.endermite: true
            SimpleEgg.guardian: true
            SimpleEgg.elderguardian: true
            SimpleEgg.silverfish: true
            SimpleEgg.slime: true
            SimpleEgg.wither: true
            SimpleEgg.shulker: true
            SimpleEgg.evoker: true
            SimpleEgg.vex: true
            SimpleEgg.vindicator: true

    SimpleEgg.magmacube:
        description: Allows capturing of this mob
    SimpleEgg.blaze:
        description: Allows capturing of this mob
    SimpleEgg.ghast:
        description: Allows capturing of this mob
    SimpleEgg.pigzombie:
        description: Allows capturing of this mob
    SimpleEgg.spider:
        description: Allows capturing of this mob
    SimpleEgg.cavespider:
        description: Allows capturing of this mob
    SimpleEgg.zombie:
        description: Allows capturing of this mob
    SimpleEgg.husk:
        description: Allows capturing of this mob
    SimpleEgg.zombievillager:
        description: Allows capturing of this mob
    SimpleEgg.skeleton:
        description: Allows capturing of this mob
    SimpleEgg.witherskeleton:
        description: Allows capturing of this mob
    SimpleEgg.creeper:
        description: Allows capturing of this mob
    SimpleEgg.witch:
        description: Allows capturing of this mob
    SimpleEgg.enderman:
        description: Allows capturing of this mob
    SimpleEgg.endermite:
        description: Allows capturing of this mob
    SimpleEgg.guardian:
        description: Allows capturing of this mob
    SimpleEgg.elderguardian:
        description: Allows capturing of this mob
    SimpleEgg.silverfish:
        description: Allows capturing of this mob
    SimpleEgg.slime:
        description: Allows capturing of this mob
    SimpleEgg.wither:
        description: Allows capturing of this mob
    SimpleEgg.shulker:
        description: Allows capturing of this mob
    SimpleEgg.evoker:
        description: Allows capturing of this mob
    SimpleEgg.vex:
        description: Allows capturing of this mob
    SimpleEgg.vindicator:
        description: Allows capturing of this mob

    #Ownership Modifications
    SimpleEgg.owner-override:
        description: Allows a player to capture a tameable mob even if someone else owns it.
    SimpleEgg.steal:
        description: Allows a player to capture and take ownership of a mob someone else owns.
        children:
            SimpleEgg.owner-override: true
    SimpleEgg.auto-tame:
        description: Allows a player to automatically tame an untamed mob when they capture it.
