main: io.github.redpanda4552.SimpleEgg.Main
name: SimpleEgg
version: 0.5.0
author: bdubz4552
description: A plugin to allow the capture and conversion of living entites to spawn eggs.
softdepend: [Vault]
api-version: 1.13

commands:
    simpleegg:
        description: Help command for SimpleEgg
        usage: /simpleegg
        aliases: se

permissions:
    # Global
    SimpleEgg.*:
        children:
            SimpleEgg.passive: true
            SimpleEgg.villager: true
            SimpleEgg.tameable: true
            SimpleEgg.monster: true
            SimpleEgg.owner-override: true
            SimpleEgg.steal: true
            SimpleEgg.auto-tame: true
            SimpleEgg.use-spawner: true
            SimpleEgg.update-notify: true

    # Admin
    SimpleEgg.update-notify:
    SimpleEgg.reload:

    # Passive
    SimpleEgg.passive:
        children:
            SimpleEgg.bat: true
            SimpleEgg.chicken: true
            SimpleEgg.cod: true
            SimpleEgg.cow: true
            SimpleEgg.dolphin:
            SimpleEgg.irongolem: true
            SimpleEgg.mushroomcow: true
            SimpleEgg.pig: true
            SimpleEgg.polarbear: true
            SimpleEgg.pufferfish: true
            SimpleEgg.rabbit: true
            SimpleEgg.salmon: true
            SimpleEgg.sheep: true
            SimpleEgg.snowman: true
            SimpleEgg.squid: true
            SimpleEgg.tropicalfish: true
            SimpleEgg.turtle: true
    SimpleEgg.bat:
    SimpleEgg.chicken:
    SimpleEgg.cod:
    SimpleEgg.cow:
    SimpleEgg.dolphin:
    SimpleEgg.irongolem:
    SimpleEgg.mushroomcow:
    SimpleEgg.pig:
    SimpleEgg.polarbear:
    SimpleEgg.pufferfish:
    SimpleEgg.rabbit:
    SimpleEgg.salmon:
    SimpleEgg.sheep:
    SimpleEgg.snowman:
    SimpleEgg.squid:
    SimpleEgg.tropicalfish:
    SimpleEgg.turtle:

    # Villager
    SimpleEgg.villager:

    # Tameable
    SimpleEgg.tameable:
        children:
            SimpleEgg.donkey: true
            SimpleEgg.horse: true
            SimpleEgg.llama: true
            SimpleEgg.mule: true
            SimpleEgg.ocelot: true
            SimpleEgg.parrot: true
            SimpleEgg.skeletonhorse: true
            SimpleEgg.wolf: true
            SimpleEgg.zombiehorse: true
    SimpleEgg.donkey:
    SimpleEgg.horse:
    SimpleEgg.llama:
    SimpleEgg.mule:
    SimpleEgg.ocelot:
    SimpleEgg.parrot:
    SimpleEgg.skeletonhorse:
    SimpleEgg.wolf:
    SimpleEgg.zombiehorse:

    # Monsters
    SimpleEgg.monster:
        children:
            SimpleEgg.blaze: true
            SimpleEgg.cavespider: true
            SimpleEgg.creeper: true
            SimpleEgg.drowned: true
            SimpleEgg.elderguardian: true
            SimpleEgg.enderman: true
            SimpleEgg.endermite: true
            SimpleEgg.evoker: true
            SimpleEgg.ghast: true
            SimpleEgg.guardian: true
            SimpleEgg.husk: true
            SimpleEgg.magmacube: true
            SimpleEgg.phantom: true
            SimpleEgg.pigzombie: true
            SimpleEgg.shulker: true
            SimpleEgg.silverfish: true
            SimpleEgg.skeleton: true
            SimpleEgg.slime: true
            SimpleEgg.spider: true
            SimpleEgg.stray: true
            SimpleEgg.vex: true
            SimpleEgg.vindicator: true
            SimpleEgg.witch: true
            SimpleEgg.wither: true
            SimpleEgg.witherskeleton: true
            SimpleEgg.zombie: true
            SimpleEgg.zombievillager: true
    SimpleEgg.blaze:
    SimpleEgg.cavespider:
    SimpleEgg.creeper:
    SimpleEgg.drowned:
    SimpleEgg.elderguardian:
    SimpleEgg.enderman:
    SimpleEgg.endermite:
    SimpleEgg.evoker:
    SimpleEgg.ghast:
    SimpleEgg.guardian:
    SimpleEgg.husk:
    SimpleEgg.magmacube:
    SimpleEgg.phantom:
    SimpleEgg.pigzombie:
    SimpleEgg.shulker:
    SimpleEgg.silverfish:
    SimpleEgg.skeleton:
    SimpleEgg.slime:
    SimpleEgg.spider:
    SimpleEgg.stray:
    SimpleEgg.vex:
    SimpleEgg.vindicator:
    SimpleEgg.witch:
    SimpleEgg.wither:
    SimpleEgg.witherskeleton:
    SimpleEgg.zombie:
    SimpleEgg.zombievillager:

    # Ownership Modifications
    SimpleEgg.owner-override:
    SimpleEgg.steal:
        children:
            SimpleEgg.owner-override: true
    SimpleEgg.auto-tame:
    
    # Other
    SimpleEgg.use-spawner:
